/**
 * EONIX MODULE FIRMWARE
 * 
 * Target: STM32F1xx / STM32G0xx / any STM32
 * 
 * Usage:
 * 1. Initialize I2C in Slave Mode (e.g. Addr = 0x10).
 * 2. Listens for I2C configuration packets from the Mainboard.
 * 3. Controls an onboard LED blinking based on the received config.
 */

 #include "main.h"
 
 /* I2C handler structure */
 I2C_HandleTypeDef hi2c1;
 
 /* The current Module specific I2C slave address 
  * Change to `(0x11 << 1)` for Mod 2, `(0x12 << 1)` for Mod 3 
  */
 #define I2C_SLAVE_ADDR  (0x10 << 1)
 
 // Global volatile variables for the hardware process
 volatile uint16_t blink_rate_ms = 500; // Default blink rate
 uint8_t i2c_rx_buffer[3];               // [Reg][ValueH][ValueL]
 
 /**
  * @brief  I2C Slave Receive complete callback.
  * @param  hi2c Pointer to a I2C_HandleTypeDef structure
  * @retval None
  * 
  * Add the function `HAL_I2C_SlaveRxCpltCallback` in your `stm32xx_it.c` to call this.
  */
 void HAL_I2C_SlaveRxCpltCallback(I2C_HandleTypeDef *hi2c)
 {
     if (hi2c->Instance == I2C1) {
         // We expect a 3-byte payload:
         // byte 0 = Register ID (0x01 means Blink Rate config)
         // byte 1 = High byte of delay ms
         // byte 2 = Low byte of delay ms
         
         if (i2c_rx_buffer[0] == 0x01) {
             uint16_t new_rate = (i2c_rx_buffer[1] << 8) | i2c_rx_buffer[2];
             if (new_rate >= 50 && new_rate <= 5000) {
                 blink_rate_ms = new_rate;
             }
         }
         
         // Restart slave listening so it receives the next Mainboard packet
         HAL_I2C_Slave_Receive_IT(&hi2c1, (uint8_t *)i2c_rx_buffer, 3);
     }
 }
 
 int main(void)
 {
     HAL_Init();
     // SystemClock_Config();
     
     // Initialize GPIO for the LED
     GPIO_InitTypeDef GPIO_InitStruct = {0};
     __HAL_RCC_GPIOC_CLK_ENABLE();
     GPIO_InitStruct.Pin = GPIO_PIN_13; // Common bluepill / STM32 board LED pin
     GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
     GPIO_InitStruct.Pull = GPIO_NOPULL;
     GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
     HAL_GPIO_Init(GPIOC, &GPIO_InitStruct);
     
     // Initialize I2C Slave
     // MX_I2C1_Init(); (Generated by CubeMX)
     // hi2c1.Init.OwnAddress1 = I2C_SLAVE_ADDR;
     
     // Start listening in Non-Blocking Interrupt mode
     HAL_I2C_Slave_Receive_IT(&hi2c1, (uint8_t *)i2c_rx_buffer, 3);
     
     uint32_t last_toggle_tick = HAL_GetTick();
     
     while (1)
     {
         // Standard blink LED process loop using the dynamic config value
         if (HAL_GetTick() - last_toggle_tick >= blink_rate_ms) {
             HAL_GPIO_TogglePin(GPIOC, GPIO_PIN_13);
             last_toggle_tick = HAL_GetTick();
         }
     }
 }
